server:
  port: 8089

endpoints:
  actuator:
    enabled: true
    sensitive: false

management:
  security:
    enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      instanceId: ${spring.application.name}:${server.port} 
    hostname: ${hostName}
      
---

spring:
  profiles: v1

eureka:
  instance:
    metadata-map:
      versions: v1
     
---

spring:
  profiles: v1v2
  
eureka:
  instance:
    metadata-map:
      versions: v1,v2  

      